### ISSUE TITLE
only

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-hvr/Only#1]
Is it intentional that this package has the same name as an existing one, besides capitalisation?

https://hackage.haskell.org/package/only

**Comment by hvr** [comment]
The clash per se wasn't intentional; otoh, it's not a big deal cause the `only` package appears to be abandoned, it's a executable-only package (thus it lives in a different category; if you accidentally `build-depend` on it, the cabal solver will complain there's no library inside) and its maintainer hasn't shown any activity on Hackage for several years now...

And fwiw, Hackage has a policy in place now which prevents to introduce new name-clashes with existing packages you don't own in the primary index.
